import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { AppContectProvider } from "@/context/AppContext";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Xinthesys",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=1"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContectProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </AppContectProvider>
      </body>
    </html>
  );
}
